//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: ContentFilteredTopicData.cpp
//  Source: ../idl/ContentFilteredTopicData.idl
//  Generated: Mon Feb  6 23:21:26 2017
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************

#include "ContentFilteredTopicData.h"




