//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: HelloWorldData.cpp
//  Source: ../../idl/HelloWorldData.idl
//  Generated: Mon Feb  6 23:21:43 2017
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************

#include "HelloWorldData.h"




