//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Chat.cpp
//  Source: ../../idl/Chat.idl
//  Generated: Fri Feb 10 16:33:20 2017
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************

#include "Chat.h"




