//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: ContentFilteredTopicData.h
//  Source: ../../idl/ContentFilteredTopicData.idl
//  Generated: Mon Feb  6 23:21:23 2017
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************
#ifndef _CONTENTFILTEREDTOPICDATA_H_
#define _CONTENTFILTEREDTOPICDATA_H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"


namespace StockMarket
{
   struct Stock;

   struct Stock
   {
         DDS::String_mgr ticker;
         DDS::Float price;
   };

   typedef DDS_DCPSStruct_var < Stock> Stock_var;
   typedef DDS_DCPSStruct_out < Stock> Stock_out;
}




#endif 
