//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Chat.cpp
//  Source: ../../idl/Chat.idl
//  Generated: Mon Feb  6 23:06:46 2017
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************

#include "Chat.h"




